### PR TITLE
Fixed Webpack Bundling Issue, Fixed React-Router Issue.

### PR DESCRIPTION
**Pull request by dashcraft**
Added React Router dependency and hoist non react statics webpack dependency to the project. Also reconfigured the startup file to reference development mode using the current syntax (--mode production 
|| --mode development).

### CODE REVIEW

**Comment by dashcraft** [comment]
Fixes #2

**Comment by dance2die** [comment]
@dashcraft Thanks Daniel 🙏 .

I've tested it and worked. I will package it up and nugetify it soon 👍

**Comment by dance2die** [comment]
I've published version 0.1.0 to nuget and added you in the README to give you a credit
🙇

**Comment by dashcraft** [comment]
Cool, thanks! I was using it for a project and ran across the issues and fixed them on my own template so through them into a pr for you.

**Comment by dance2die** [comment]
I honestly haven't been using .NET core much (as I've been focused on React) so the PR really helped.

**Comment by dashcraft** [comment]
Let me know if you run into any other issues. I also don't use .NET core on a daily basis, i'm doing mostly fullstack js for my clients and customers. However, you have to have a vetted solution to become a microsoft partner, so here i am plugging away at some C#.

**Pull request merged**
